server:
  port: 8070
  undertow:
    threads:
      io: 4
      worker: 32
    buffer-size: 1MB
    direct-buffers: true
    max-http-post-size: 10MB
  max-http-header-size: 1MB # Sevlet maximum size of the HTTP message header. Default 8KB
spring:
  application:
    name: message-server
  main:
    allow-bean-definition-overriding: true
  cloud:
    function:
      definition: systemSafety;bookCrawlSource;systemCommand
    stream:
      bindings:
        systemSafety-in-0:
          destination: system-safety-topic
        bookCrawlSource-in-0:
          destination: book-crawl-source-topic
        systemCommand-in-0:
          destination: system-command-topic
  datasource:
    druid:
      url: jdbc:mysql://mysql.sqlpub.com:3306/kouleen?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: kouleen
      password: dbc11fd168d37962
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-active: 30
      min-idle: 3
      initial-size: 3
      validation-query: select 1
      max-wait: 5000
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        allow:
        deny:
        url-pattern:
          - /druid/*
  cache:
    redis:
      time-to-live: 864000000
  mail:
    host: smtp.qq.com
    port: 465
    username: 582821086@qq.com
    password: dqqwjpujsixybbih
    test-connection: true
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          starttls:
            enable: true
            required: true
  rabbitmq:
    host: seal.lmq.cloudamqp.com
    port: 5672
    username: qffnscoh
    password: AHqQaA_Bh9eR6szbOMmcn_1nBCk0K5AB
    virtual-host: qffnscoh
  redis:
    host: library.kouleen.cn
    port: 6379
    password: zhangqing5240
    database: 1
  data:
    mongodb:
      uri: mongodb://kouleen:zhangqing5240@library.kouleen.cn:27017/admin
      # uri: mongodb+srv://kouleen:zhangqing5240@kouleen.an5tffl.mongodb.net/admin?retryWrites=true&w=majority
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    - classpath:mappers/**/*.xml
swagger:
  enable: true
auth:
  username: kouleen
  password: zhangqing5240